---
# Server-Zertifikat für Gateway (TLS + mTLS)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slainte-intranet-tls-secret
  namespace: istio-gateways
spec:
  secretName: slainte-intranet-tls-secret
  dnsNames:
    - "*.slainte.at"
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
    - server auth
  duration: 2160h        # 90d
  renewBefore: 360h      # 15d
  privateKey:
    algorithm: RSA
    size: 2048
---
#1) Zertifikate
#A) Apex slainte.at via Lets Encrypt (cert-manager)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slainte-at
  namespace: istio-gateways
spec:
  secretName: slainte-at-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "slainte.at"
---
# B) Wildcard *.slainte.at via deiner CA k8s-issuer (für mTLS)
# Das ist dein Server-Zertifikat für den mTLS-Listener.
# (Hier ist der wichtige Punkt: Bei CA-Issuern landet typischerweise auch ca.crt im Secret, was Istio für MUTUAL braucht.)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-slainte-at-mtls
  namespace: istio-gateways
spec:
  secretName: wildcard-slainte-at-mtls-credential
  issuerRef:
    kind: ClusterIssuer
    name: k8s-issuer
  dnsNames:
  - "*.slainte.at"    
  usages:
    - digital signature
    - key encipherment
    - server auth
  duration: 2160h        # 90d
  renewBefore: 360h      # 15d
  privateKey:
    algorithm: RSA
    size: 2048
---
