---
# Server-Zertifikat für Gateway (TLS + mTLS)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slainte-intranet-tls-secret
  namespace: istio-system
spec:
  secretName: slainte-intranet-tls-secret
  dnsNames:
    - "*.slainte.at"
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - server auth
  duration: 2160h        # 90d
  renewBefore: 360h      # 15d
  privateKey:
    algorithm: RSA
    size: 2048
---
# Client-CA-Zertifikat (für mTLS Clients)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slainte-intranet-client-secret
  namespace: istio-system
spec:
  isCA: true
  secretName: slainte-intranet-client-secret
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: internal-clients
---
