-
  name: 'Playbook setting network settings for MicroCloud'
  hosts: all
  become: True
  become_method: sudo
  tasks:
    - name: copying Network-Config
      become: true
      copy:
        src: ./50-cloud-init.yaml
        dest: /etc/netplan/
        owner: root
        group: root
        mode: 0600
    - name: Set Mac-Address to hw-address of eno1
      become: true
      ansible.builtin.shell: sed -i "s/99:99:99:99:99:99/$(cat /sys/class/net/eno1/address)/g" /etc/netplan/50-cloud-init.yaml