-
  name: 'Playbook setting network settings for MicroCloud'
  hosts: all
  become: True
  become_method: sudo
  tasks:
    - name: copying Network-Config
      become: true
      copy:
        src: ./50-cloud-init.yaml
        dest: /etc/netplan/
        owner: root
        group: root
        mode: 0600
    - name: Set correct IP address in netplan config
      become: true
      ansible.builtin.shell: sed -i "s/192.168.0.xxx/{{ hostvars[inventory_hostname].ip }}/g" /etc/netplan/50-cloud-init.yaml