-
  name: 'Richtiges Setzen der IP-Einträge im Hosts-file /etc/hosts'
  hosts: all
  become: True
  become_method: sudo
  tasks:
    - name: "Remove any existing localhost entry"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1'
        state: absent
        owner: root
        group: root
        mode: '0644'
    - name: "Remove any existing localhost entry"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        state: absent
        owner: root
        group: root
        mode: '0644'
    - name: 'add omv'
      lineinfile:
        path: /etc/hosts
        regexp: '^omv.slainte.at'
        line: '192.168.0.10 omv.slainte.at omv'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add k1'
      lineinfile:
        path: /etc/hosts
        regexp: '^k1.slainte.at'
        line: '192.168.0.191 k1.slainte.at k1'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add k2'
      lineinfile:
        path: /etc/hosts
        regexp: '^k2.slainte.at'
        line: '192.168.0.192 k2.slainte.at k2'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add k3'
      lineinfile:
        path: /etc/hosts
        regexp: '^k3.slainte.at'
        line: '192.168.0.193 k3.slainte.at k3'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add k4'
      lineinfile:
        path: /etc/hosts
        regexp: '^k4.slainte.at'
        line: '192.168.0.194 k4.slainte.at k4'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: "Replace a localhost entry with our own"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        line: "127.0.0.1 {{ inventory_hostname }}\n127.0.0.1 localhost"
        state: present
        owner: root
        group: root
        mode: '0644'

