-
  name: 'Richtiges Setzen der IP-Einträge im Hosts-file /etc/hosts'
  hosts: microcloud
  become: True
  become_method: sudo
  tasks:
    - name: "Remove any existing localhost entry"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1'
        state: absent
        owner: root
        group: root
        mode: '0644'
    - name: "Remove any existing localhost entry"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        state: absent
        owner: root
        group: root
        mode: '0644'
    - name: 'add omv'
      lineinfile:
        path: /etc/hosts
        regexp: '^omv.slainte.at'
        line: '192.168.0.10 omv.slainte.at omv'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add micro1'
      lineinfile:
        path: /etc/hosts
        regexp: '^micro1.slainte.at'
        line: '192.168.0.191 micro1.slainte.at micro1'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add micro2'
      lineinfile:
        path: /etc/hosts
        regexp: '^micro2.slainte.at'
        line: '192.168.0.192 micro2.slainte.at micro2'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add micro3'
      lineinfile:
        path: /etc/hosts
        regexp: '^micro3.slainte.at'
        line: '192.168.0.193 micro3.slainte.at micro3'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: 'add micro4'
      lineinfile:
        path: /etc/hosts
        regexp: '^micro4.slainte.at'
        line: '192.168.0.194 micro4.slainte.at micro4'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: "Replace a localhost entry with our own"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        line: "127.0.0.1 {{ inventory_hostname }}\n127.0.0.1 localhost"
        state: present
        owner: root
        group: root
        mode: '0644'

