-
  name: 'setzen des hostnames auf den richtigen Namen'
  hosts: microcloud
  become: yes
  become_method: sudo
  tasks:
    - name: "Update Hostname"
      hostname:
        name: "{{ inventory_hostname }}"
