-
  name: 'Disable apparmor for MicroCloud'
  hosts: microcloud
  become: True
  become_method: sudo
  tasks:
    - name: "Remove any existing linux-boot-line"
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX'
        state: absent
        owner: root
        group: root
        mode: '0644'
    - name: "apparmor diaabling"
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX'
        line: 'GRUB_CMDLINE_LINUX="apparmor=0"'
        state: present
        owner: root
        group: root
        mode: '0644'
    - name: "Update grub"
      ansible.builtin.shell: sudo update-grub
      args:
        executable: /bin/bash
    - name: Reboot machine and send a message
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
    - name: Wait 300 seconds, but only start checking after 15 seconds
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300
