---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: openbao
  name: openbao-softhsm-secret
  namespace: ${NAMESPACE}
data:
  USER_PIN: ${K8S_OPENBAO_USER_PIN}
  SO_PIN: ${K8S_OPENBAO_SO_PIN}
---