---
# softhsm-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softhsm
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softhsm
  template:
    metadata:
      labels:
        app: softhsm
    spec:
      containers:
      - name: softhsm
        image: alpine:latest
        volumeMounts:
          - name: softhsm-data
            mountPath: /var/lib/softhsm
        env:
          - name: SOFTHSM2_CONF
            value: "/etc/softhsm2.conf"
        command:
          - "sh"
          - "-c"
          - |
            apk update && apk upgrade && \
            apk add --update tzdata && \
            cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && \
            echo "Europe/Vienna" > /etc/timezone && \
            apk add --no-cache softhsm && \
            softhsm2-util --init-token --free --label "OpenbaoToken" --pin 1234 --so-pin 123456 && \
            sleep infinity
        #ports:
        #- containerPort: 8080
        # Note: The container does not need open ports unless you plan for remote mgmt
      volumes:
      - name: softhsm-data
        persistentVolumeClaim:
          claimName: softhsm-pvc
---