---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-depl
  namespace: default
spec:
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      # Container Spec
      containers:
        - name: busybox
          image: ${K8S_REGISTRY}/tools/busybox:latest
          imagePullPolicy: Always
---