---
# ServiceMonitor for cert-manager to enable Prometheus scraping of its metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: observability
  labels:
    release: kube-prom-stack # label used by kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cert-manager # Label used by cert-manager service
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-metrics
    interval: 15s
    scrapeTimeout: 10s
---