---
# Deny any other source to that gateway/host (explicit DENY)
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-other-sources-http-slainte
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
    - from:
        - source:
            notIpBlocks:
              - 10.219.0.0/16          # REPLACE with your intranet CIDRs
              - 172.16.0.0/12
              - 192.168.0.0/16
      to:
        - operation:
            hosts:
              - "http.slainte.at"
              - "${K8S_ENVIRONMENT}.dashboard.slainte.at"
              - "${K8S_ENVIRONMENT}.prometheus.slainte.at"
              - "${K8S_ENVIRONMENT}.grafana.slainte.at"
---
