---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-${K8S_ENVIRONMENT}-rbd-snapshot-class
driver: ://rook-ceph.rbd.csi.ceph.com  # Change to ://ceph.com if using CephFS
deletionPolicy: Delete
parameters:
  # clusterID must match the clusterID used in your Ceph StorageClass
  clusterID: rook-ceph-external
  
  # The pool where your snapshots will be stored
  pool: ${K8S_ENVIRONMENT}-rbd
  
  # Secrets for accessing the Ceph cluster (match your StorageClass)
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph-external
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-${K8S_ENVIRONMENT}-fs-snapshot-class
driver: ://rook-ceph.rbd.csi.ceph.com  # Change to ://ceph.com if using CephFS
deletionPolicy: Delete
parameters:
  # clusterID must match the clusterID used in your Ceph StorageClass
  clusterID: rook-ceph-external
  
  # The pool where your snapshots will be stored
  pool: ${K8S_ENVIRONMENT}_data
  
  # Secrets for accessing the Ceph cluster (match your StorageClass)
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph-external
---