apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: duplicity-backup-credentials
  namespace: duplicity
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-duplicity
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
    openbao.mount: kv
    openbao.key: duplicity-duplicity-backup-credentials
spec:
  provider: openbao
  parameters:
    openbaoAddress: http://openbao.openbao.svc:8200
    openbaoKVVersion: '2'
    roleName: duplicity-role
    objects: |2-
        - objectName: username
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: username
        - objectName: password
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: password
        - objectName: notes
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: notes
        - objectName: s3AccessKey
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: s3AccessKey
        - objectName: s3SecretKey
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: s3SecretKey
        - objectName: sshHost
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: sshHost
        - objectName: sshPort
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: sshPort
        - objectName: sshRemotePath
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: sshRemotePath
        - objectName: sshUser
          secretPath: secret/data/duplicity/duplicity-backup-credentials
          secretKey: sshUser
