---
# This is an example of a Kubernetes Deployment that uses a PersistentVolumeClaim to write logs to an ceph shared storage.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bbrook
    storage: rook
  name: bbrook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbrook
  template:
    metadata:
      labels:
        app: bbrook
    spec:
      containers:
      - image: busybox
        name: bbrook
        command: ["/bin/sh"]
        args: ["-c","sleep 3600"]
        volumeMounts:
          - name: rook
            mountPath: "/mnt/rook"
      volumes:
      - name: rook
        persistentVolumeClaim:
          claimName: rook
