---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook
  namespace: default
  labels:
    app: bbrook
    storage: rook
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Mi
---