---
# Reserve Disk Space for kube-prometheus-stack
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-storage-pvc
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd   # adjust to your RBD StorageClass
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-dashboard-pvc
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd   # adjust to your RBD StorageClass
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-datasources-pvc
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd   # adjust to your RBD StorageClass
  resources:
    requests:
      storage: 5Gi
---