---
# Reserve Disk Space for kube-prometheus-stack
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-storage-pvc
  namespace: observability
  labels:
    app.kubernetes.io/instance: kube-prom-stack
    storage: rook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10G
  volumeName: kube-prom-storage-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-sc-dashboard-volume-pvc
  namespace: observability
  labels:
    app.kubernetes.io/instance: kube-prom-stack
    storage: rook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10G
  volumeName: kube-prom-sc-dashboard-volume-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-sc-datasources-volume-pvc
  namespace: observability
  labels:
    app.kubernetes.io/instance: kube-prom-stack
    storage: rook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10G
  volumeName: kube-prom-sc-datasources-volume-pv
---