---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    kubernetes.io/metadata.name: vault
  # Uncomment if using Linkerd
  # annotations:
  #   linkerd.io/inject: enabled
spec:
  finalizers:
    - kubernetes
---