# https://cert-manager.io/docs/usage/certificate/
---
# The Certificate should be created in the same namespace as the istio-ingressgateway deployment.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpecho
  namespace: istio-system
spec:
  isCA: false
  isCA: false
  # Avoid using commonName for DNS names in end-entity (leaf) certificates. Unless you have a specific
  # need for it in your environment, use dnsNames exclusively to avoid issues with commonName.
  # Usually, commonName is used to give human-readable names to CA certificates and can be avoided for
  # other certificates.
  #commonName: httpecho
  secretName: httpecho
  duration: 2160h        # 90 days
  renewBefore: 360h      # 15 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: k8s-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - ${K8S_ENVIRONMENT}.http-echo-simple.slainte.at
  emailAddresses:
    - slainte@slainte.at
  # Needs cert-manager 1.14+ and "OtherNames" feature flag
  subject:
    organizations:
      - ${K8S_ENVIRONMENT}
    organizationalUnits:
      - http-echo-simple.slainte.at
  usages:
    - digital signature
    - key encipherment
    - server auth
---
# Client Certificate for Mutual TLS - specific for alfred@slainte.at
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alfred-at-slainte-at
  namespace: istio-system
spec:
  isCA: false
  # Avoid using commonName for DNS names in end-entity (leaf) certificates. Unless you have a specific
  # need for it in your environment, use dnsNames exclusively to avoid issues with commonName.
  # Usually, commonName is used to give human-readable names to CA certificates and can be avoided for
  # other certificates.
  #commonName: alfred-at-slainte-at
  secretName: alfred-at-slainte-at
  duration: 2160h        # 90 days
  renewBefore: 360h      # 15 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: k8s-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
# At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - ${K8S_ENVIRONMENT}.http-echo-simple.slainte.at
  emailAddresses:
    - alfred@slainte.at
  # Needs cert-manager 1.14+ and "OtherNames" feature flag
  subject:
    organizations:
      - Slainte-IT
    organizationalUnits:
      - Engineering
  usages:
    - digital signature
    - key encipherment
    - client auth
---