---
# The Certificate should be created in the same namespace as the istio-ingressgateway deployment.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpecho
  namespace: istio-system
spec:
  isCA: false
  commonName: httpecho
  secretName: httpecho
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - ${K8S_ENVIRONMENT}.http-echo-simple.slainte.at
  usages:
    - digital signature
    - key encipherment
    - server auth
---
# Client Certificate for Mutual TLS - specific for alfred@slainte.at
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alfred@slainte.at
  namespace: istio-system
spec:
  secretName: alfred@slainte.at
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: alfred@slainte.at
  emailAddresses:
    - alfred@slainte.at
  subject:
    organizations:
      - internal
    organizationalUnits:
      - Engineering
  usages:
    - digital signature
    - key encipherment
    - client auth
  duration: 2160h        # 90 days
  renewBefore: 360h      # 15 days
  ---