---
# Configure Gateway and VirtualService resources for httpecho with mutual TLS:
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: httpecho-gateway
  namespace: demo-istio
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "${K8S_ENVIRONMENT}.http-echo-simple.slainte.at"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests    
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpecho-credential # must be the same as secret
    hosts:
    - "${K8S_ENVIRONMENT}.http-echo-simple.slainte.at"
---