---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpecho-credential
  namespace: demo-istio
spec:
  isCA: false
  commonName: httpecho-credential
  secretName: httpecho-credential
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---