---
# This Service exposes the http-echo deployment within the demo-istio namespace.
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: demo-istio
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5678
  selector:
    app: http-echo
  sessionAffinity: None
  type: ClusterIP
---
