apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-echo-gateway
  namespace: demo-istio  
  annotations:
    # Beschränkt externe Zugriffe auf interne Netze (Cloud / MetalLB / LB abhängig)
    service.beta.kubernetes.io/load-balancer-source-ranges: |
    service.beta.kubernetes.io/load-balancer-source-ranges: |
      10.219.0.0/16,
      10.242.0.0/16,
      172.16.0.0/12,
      192.168.0.0/16    
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: ${K8S_ENVIRONMENT}-http-echo
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-echo-route
  namespace: demo-istio  
spec:
  parentRefs:
  - name: http-echo-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: http-echo
      port: 80
---