
    packages:
      - bash
      - openssh
      - nano
      - mc
      - dnsmasq
      - sudo

    # https://wiki.alpinelinux.org/wiki/OpenRC
    runcmd:
      - |
        rc-update add dnsmasq default
        rc-service dnsmasq start
        rc-update add sshd default
        rc-service sshd start
 
  # https://documentation.ubuntu.com/lxd/latest/cloud-init/#how-to-specify-network-configuration-data
  cloud-init.network-config: |
    version: 2
    ethernets:
      eth0:
        dhcp4: false
        dhcp6: true
        addresses:     # Static IP address
          - 10.139.121.5/24


