server:
        ip-address: 10.139.121.5
        port: 8853
        #server-count: 1
        #ip4-only: yes
        #hide-version: yes
        #identity: ""
        #zonesdir: "/etc/nsd"

remote-control:
  control-enable: yes
  
zone:
        name: "lxd.slainte.at"
        request-xfr: AXFR 10.139.121.1@8853 NOKEY

zone:
        name: "121.139.10.in-addr.arpa"
        request-xfr: AXFR 10.139.121.1@8853 NOKEY

zone:
        name: "a.f.8.3.3.4.3.4.1.9.3.9.2.4.d.f.ip6.arpa"
        request-xfr: AXFR 10.139.121.1@8853 NOKEY
