---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpg
  namespace: slainte
  labels:
    app: gpg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpg
  template:
    metadata:
      labels:
        app: gpg
    spec:
      containers:
        - name: gpg
          image: registry.k8s.slainte.at/examples/gpg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gpg
  namespace: slainte
spec:
  selector:
    app: gpg
  ports:
    - port: 80
      targetPort: 80
---