apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  alfred-slainte-at-cert
  namespace: istio-system
spec:
  commonName: alfred@slainte.at
  usages:
    - client auth # <--- Wichtig für Curl
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always    
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: k8s-intermediate-issuer # <--- Nutzt dieselbe CA wie das Gateway
  secretName: alfred-slainte-at-tls
  duration: 8760h        # 365 days
  renewBefore: 360h      # 15 days

  ###

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smime-certificate
  namespace: default
spec:
  secretName: my-smime-secret
  # Die E-Mail-Adresse für das S/MIME-Zertifikat
  emailAddresses:
    - info@ihredomain.de
  # Gemeinsamer Name (wird oft als Anzeigename im Mail-Client genutzt)
  commonName: Max Mustermann
  duration: 2160h # 90 Tage
  renewBefore: 360h # 15 Tage vor Ablauf erneuern
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  # Essentiell für S/MIME (Client-Auth & Mail-Schutz)
  usages:
    - digital signature
    - key encipherment
    - client auth
    - email protection
  issuerRef:
    name: mein-ca-issuer # Name Ihres bestehenden Issuers
    kind: Issuer
Verwende Code mit Vorsicht.