  limits.memory: 1GiB
  snapshots.schedule.stopped: 'true'
  snapshots.schedule: '@weekly'
  snapshots.expiry: 4w
config:
  cloud-init.user-data: |
    #cloud-config
    locale: C.UTF-8
    timezone: Europe/Vienna
    package_update: true
    package_upgrade: true
    package_reboot_if_required: true
    packages:
      - bash
      - openssh
      - nano
      - mc
      - ansible
      - python3
      - sudo

    groups:
      - admingroup: [root,sys]
      - ansible

    users:
    - name: ansible
      gecos: Ansible User
      primary_group: ansible
      groups: users,admin, ansible
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      shell: /bin/bash
      lock_passwd: false
      passwd: $6$rounds=4096$u2z3kUnvB6v9VK6Q$MugQ.vCoUVSGPkCOOCOW5Yk1UJlyMaq6k4LT2ra0BMwdcr56GmJxfLwYI6ZY8dr1wZDvpJwDFpXoiZbe8sJ3l.
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ0NXq5Sy99xHSnfazUZhywcwjNmR/DP+XWZI1jP4AvS ansible@ansible"

    ssh_pwauth: false
    write_files:
      # This file is ./90-sshd.conf generated by ./InstanceGenerator/filegenerator.sh
      - path: /etc/ssh/sshd_config.d/90-sshd.conf
        owner: root:root
        permissions: 0o600
        defer: true
        encoding: base64
        content: |
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKIwojIFNldHRpbmdzIGZvciBzc2hk
          CiMKIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKUHJvdG9jb2wgMgpBZGRyZXNz
          RmFtaWx5IGFueQpQb3J0IDIyCkNsaWVudEFsaXZlSW50ZXJ2YWwgMzAwMDAKQ2xpZW50QWxpdmVD
          b3VudE1heCA1MApJZ25vcmVSaG9zdHMgeWVzCkhvc3RiYXNlZEF1dGhlbnRpY2F0aW9uIG5vCkNo
          YWxsZW5nZVJlc3BvbnNlQXV0aGVudGljYXRpb24gbm8KWDExRm9yd2FyZGluZyB5ZXMKWDExRGlz
          cGxheU9mZnNldCAxMApUQ1BLZWVwQWxpdmUgeWVzCkFjY2VwdEVudiBMQU5HIExDXyoKTG9naW5H
          cmFjZVRpbWUgMm0KUGVybWl0Um9vdExvZ2luIG5vClN0cmljdE1vZGVzIG5vCk1heEF1dGhUcmll
          cyA2Ck1heFNlc3Npb25zIDEwClBlcm1pdEVtcHR5UGFzc3dvcmRzIG5vCkFsbG93R3JvdXBzIHVz
          ZXJzIGFkbWluIGFuc2libGUKQWxsb3dVc2VycyBhbnNpYmxlCkFsbG93VGNwRm9yd2FyZGluZyBu
          bwpDb21wcmVzc2lvbiBubwpBdXRob3JpemVkS2V5c0ZpbGUgfi8uc3NoL2F1dGhvcml6ZWRfa2V5
          cwpQdWJrZXlBdXRoZW50aWNhdGlvbiB5ZXMKUGFzc3dvcmRBdXRoZW50aWNhdGlvbiBubwojIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwo=

      # This file is /lsd_init.sh generated by /filegenerator.sh
      - path: /root/lsd_init.sh
        owner: root:root
        permissions: 0o755
        defer: true
        encoding: base64
        content: |
          IyEvYmluL2Jhc2gKIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKIyBJbml0aWFs
          aXplIExpbnV4IFN0YW5kYXJkIERpcmVjdG9yeSBzdHJ1Y3R1cmUKIyBodHRwczovL2VuLndpa2lw
          ZWRpYS5vcmcvd2lraS9GaWxlc3lzdGVtX0hpZXJhcmNoeV9TdGFuZGFyZAojIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
          IyMjIyMjIyMjIyMjIyMjIyMjIyMjIwojc2hvcHQgLW8gLXMgZXJyZXhpdCAjIFRlcm1pbmF0ZXMg
          IHRoZSBzaGVsbCBzY3JpcHQgaWYgYSBjb21tYW5kIHJldHVybnMgYW4gZXJyb3IgY29kZS4KI3No
          b3B0IC1vIC1zIHh0cmFjZSAgIyBEaXNwbGF5cyBlYWNoIGNvbW1hbmQgYmVmb3JlIGl0IGlzIGV4
          ZWN1dGVkLgpzaG9wdCAtbyAtcyBub3Vuc2V0ICAjIE5vIFZhcmlhYmxlcyB3aXRob3V0IGRlZmlu
          aXRpb24KCm1vdmVfZGlyKCkgeyAgICAgICAgICAgICAKICAgIGVjaG8gIiQwIHdpbGwgbW92ZSAn
          JHsxfScgdG8gL2RhdGEgYW5kIGNyZWF0ZSBhIHN5bWxpbmsiOwoKICAgIGlmIFsgLWQgL2RhdGEv
          JHsxfSBdOyB0aGVuCiAgICAgICAgZWNobyAiL2RhdGEvJHsxfSBleGlzdHMiCiAgICBlbHNlCiAg
          ICAgICAgZWNobyAiL2RhdGEvJHsxfSBkb2VzIG5vdCBleGlzdCAtIGNyZWF0aW5nIGl0IgogICAg
          ICAgIG12IC1mICR7MX0gL2RhdGEvJHsxfSB8fCB0cnVlCiAgICBmaQoKICAgIGlmIFsgLWQgLyR7
          MX0gXTsgdGhlbgogICAgICAgIGVjaG8gIi8kezF9IGV4aXN0cyAtIHJlbW92aW5nIGl0IgogICAg
          ICAgIG12IC1mICR7MX0gLyR7MX1fYmFja3VwIHx8IHRydWUKICAgIGZpCiAgICBpZiBbIC1MIC8k
          ezF9IF07IHRoZW4KICAgICAgICBlY2hvICIvJHsxfSBpcyBhbHJlYWR5IGEgc3ltbGluayIKICAg
          IGVsc2UKICAgICAgICBlY2hvICIvJHsxfSBpcyBub3QgYSBzeW1saW5rIC0gY3JlYXRpbmcgaXQi
          CiAgICAgICAgbG4gLXMgL2RhdGEvJHsxfSAvJHsxfQogICAgZmkKfSAgIAoKbW92ZV9kaXIgaG9t
          ZQptb3ZlX2RpciB2YXIKbW92ZV9kaXIgdG1wCgplY2hvICJEaXJlY3RvcmllcyBtb3ZlZCIK

      - path: /home/ansible/.ssh/id_ed25519
        owner: ansible:ansible
        permissions: 0o600
        defer: true
        encoding: base64
        content: |
          LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
          QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhP
          UUFBQUNDZERWNnVVc3ZmY1IwcDMyczFHWWNzSE1JelprZnd6L2wxbVNOWXorQUwwZ0FBQUpqOXhM
          R0gvY1N4Cmh3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ2REVjZ1VXN2ZmNSMHAzMnMxR1ljc0hN
          SXpaa2Z3ei9sMW1TTll6K0FMMGcKQUFBRUIzbVZhUmV0M1hJTTlheUJLVTU1N2tIb29pckE0aHpj
          VTR5bkpybXkvVnJwME5YcTVTeTk5eEhTbmZhelVaaHl3Ywp3ak5tUi9EUCtYV1pJMWpQNEF2U0FB
          QUFEMkZ1YzJsaWJHVkFZVzV6YVdKc1pRRUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZB
          VEUgS0VZLS0tLS0K

      - path: /home/ansible/.ssh/id_ed25519.pub
        owner: ansible:ansible
        permissions: 0o600
        defer: true
        encoding: base64
        content: |
          c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUowTlhxNVN5OTl4SFNuZmF6VVpo
          eXdjd2pObVIvRFArWFdaSTFqUDRBdlMgYW5zaWJsZUBhbnNpYmxlCg==

      # This file is ./README.md generated by ../../InstanceGenerator/filegenerator.sh
      - path: /home/ansible/README.md
        owner: ansible:ansible
        permissions: 0o600
        defer: true
        encoding: base64
        content: |
          IyBBbnNpYmxlIE1hc3RlciBJbWFnZQoKQWltIGlzIHRvIGdlbmVyYXRlIHRoZSBhbnNpYmxlIG1h
          c3RlciBpbWFnZS4KSGVyZSBhcmUgYWxsIHRoZSBuZWNlc3Nhcnkgc2V0dGluZ3MgaW5jbHVkZWQu
          CgpgYGBgYmFzaApwZD0iL2hvbWUvYWxmcmVkL1ZTQ29kZS9taWNyb2s4cy11YnVudHUvc2V0dXAv
          TWljcm9DbG91ZC9JbnN0YW5jZUdlbmVyYXRvciIKcHl0aG9uMyAke3BkfS9pbnN0YW5jZWdlbmVy
          YXRvci5weSBcCiAgICAtLXByb2plY3Q9ZGVmYXVsdCBcCiAgICAtLXByb2ZpbGU9aW5mcmFzdHJ1
          Y3R1cmUgXAogICAgLS1pbWFnZT0iYWxwaW5lIiBcCiAgICAtLXRlbXBsYXRlX2Rpcj0ke3BkfS90
          ZW1wbGF0ZSBcCiAgICAtLW5hbWU9YW5zaWJsZQpgYGBgCgpTZXQgdGhlIERpcmVjdG9yeSByaWdo
          dCBmb3Igc3RhcnRpbmcgdGhlIGNvcnJlY3QgcHl0aG9uLgoKQW5zaWJsZSBpdHNlbGYgc2hvdWQg
          YmUgb3JnYW5pemVkIHdlbGwuIENvbmZpZ3VyYXRpb24gc2hvdWxkIGJlIHNldCB1cCBhY2NvcmRp
          bmcgdG8gaHR0cHM6Ly9kb2NzLmFuc2libGUuY29tL2Fuc2libGUvbGF0ZXN0L3JlZmVyZW5jZV9h
          cHBlbmRpY2VzL2NvbmZpZy5odG1sIAoKQXMgYW4gaWRlYSBmb3IgdGhlIHN0cnVjdHVyZSBzZWUg
          aHR0cHM6Ly9kb2NzLmFuc2libGUuY29tL2Fuc2libGUvbGF0ZXN0L3RpcHNfdHJpY2tzL3NhbXBs
          ZV9zZXR1cC5odG1sCgpBbnNpYmxlIG1vZHVsZXMgY2FuIGJlIGZvdW5kIG9uIGh0dHBzOi8vZG9j
          cy5hbnNpYmxlLmNvbS9hbnNpYmxlL2xhdGVzdC9tb2R1bGVfcGx1Z2luX2d1aWRlL2luZGV4Lmh0
          bWwKClRlbXBsYXRlcyBjYW4gYmUgZm91bmQgb24gaHR0cHM6Ly9naXRodWIuY29tL2Rldm9wc2hv
          YmJpZXMvYW5zaWJsZS10ZW1wbGF0ZXMvdHJlZS9tYXN0ZXIKCkEgbGlzdCBvZiBhbGwgTW9kdWxl
          cyBpcyBvbiBodHRwczovL2RvY3MuYW5zaWJsZS5jb20vYW5zaWJsZS8yLjkvbW9kdWxlcy9saXN0
          X29mX2FsbF9tb2R1bGVzLmh0bWwKCkEgY2hlYXQtbGlzdCBmb3IgdGhlIGNvbW1hbmQgdXNhZ2Ug
          aXMgb24gaHR0cHM6Ly9kb2NzLmFuc2libGUuY29tL2Fuc2libGUvbGF0ZXN0L2NvbW1hbmRfZ3Vp
          ZGUvY2hlYXRzaGVldC5odG1sIA==
    # https://wiki.alpinelinux.org/wiki/OpenRC
    runcmd:
      - |
        rc-update add sshd default
        rc-service sshd start
      - |
        echo "Run /root/lsd_init.sh to create the LSD standard directories" && \
        /root/lsd_init.sh && \
        ls -l / && \
        ls -l /data && \
        df -h /data
