---
# Sidecar in restrict egress to local services + system namespaces + observability services
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: kiali-sidecar
  namespace: istio-system
spec:
  egress:
    - hosts:
        - "*/*"                             # services in all namespaces
---