-
  name: 'Playbook for applying original cloud-init configuration'
  hosts: all
  become: True
  become_method: sudo
  tasks:
    - name: copying 50-cloud-init-original.yaml
      become: true
      copy:
        src: 50-cloud-init-original.yaml
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: 0600
    - name: "Apply Netplan"
      ansible.builtin.shell: sudo netplan apply
      args:
        executable: /bin/bash        
    - name: Reboot machine and send a message
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
    - name: Wait 300 seconds, but only start checking after 15 seconds
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300
