---
# https://headlamp.dev/docs/latest/installation/
# Creates a cluster-admin ServiceAccount and ClusterRoleBinding for headlamp login.
# WARNING: This grants full cluster admin rights. Use only for testing or trusted environments.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: kube-system
  labels:
    role: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp-admin
    namespace: kube-system
---
#Getting a long-lived Bearer Token for ServiceAccount
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "headlamp-admin" # Must match the ServiceAccount name
type: kubernetes.io/service-account-token
# kubectl get secret headlamp-admin -n kube-system -o jsonpath="{.data.token}" | base64 -d
