apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-ui-sa
  namespace: velero-ui
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: velero-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-ui-writer
  namespace: velero-ui
  labels:
    security: cis
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: velero-ui
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasspodstatuses
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-ui-swb
  namespace: velero-ui
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: velero-ui
roleRef:
  kind: Role
  name: velero-ui-writer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: velero-ui-sa
    namespace: velero-ui
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: velero-ui-eso
  namespace: velero-ui
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: velero-ui
    external-secrets.io/ignore-maintenance-checks: 'true'
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc:8200
      version: v2
      path: secret
      auth:
        kubernetes:
          mountPath: kubernetes
          role: velero-ui-role
          serviceAccountRef:
            name: velero-ui-sa
