apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: velero
  namespace: velero
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-velero
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
data:
  cloud: 
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPTVmNDgwZjA5NThjYTU1N2E0YmE1CmF3c19zZWNyZXRfYWNjZXNzX2tleT1Pc3FpVEtZK2RKOXhqRVFSaW5QRVU5UVkrVzhaejVPZndCUlNydXJPb1RRPQ==