---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: ${K8S_ENVIRONMENT}-velero
  namespace: velero
  annotations:
    meta.helm.sh/release-name: velero
    meta.helm.sh/release-namespace: velero
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: 1.18.1
    helm.sh/chart: velero-12.1.0
spec:
  provider: csi
  config:
    region: ${S3_REGION}
    s3ForcePathStyle: "true"
    s3Url: ${S3_ENDPOINT}
  credential:
    key: cloud
    name: velero
---