---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: ${K8S_ENVIRONMENT}-velero
  namespace: velero
spec:
  provider: csi
  config:
    region: default
    s3ForcePathStyle: "true"
    s3Url: http://192.168.0.194:8081
  credential:
    key: cloud
    name: velero
---
