---
# Backup all namespaces every day at 2am, keep for 3 days.
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule-namespaces
  namespace: velero
spec:
  paused: false
  schedule: CRON_TZ=Europe/Vienna 0 2 * * *
  skipImmediately: false
  template:
    defaultVolumesToFsBackup: true
    includeClusterResources: true
    includedNamespaces:
      - "*"
    includedResources:
      - "*"
    snapshotVolumes: true
    storageLocation: ${VELERO_BACKUP_LOCATION_NAME}
    ttl: 72h
    volumeSnapshotLocations:
      - ${VELERO_BACKUP_LOCATION_NAME}
  useOwnerReferencesInBackup: true
---