apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-test-pvc
  namespace: rook-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # Replace storageClassName with the CephFS StorageClass in your cluster
  storageClassName: rook-cephfs