
      # Explanation of structure
      - path: /home/ansible/README.md
        owner: ansible:ansible
        permissions: 0o600
        defer: true
        encoding: base64
        content: files/README.md

      # Configuration of known hosts
      - path: /etc/hosts
        owner: root:root
        permissions: 0o644
        defer: true
        encoding: base64
        content: files/hosts


