name: UbuntuCloudMacVLan
description: Nginx Proxy Manager https://nginxproxymanager.com/
type: container
project: default
architecture: x86_64
ephemeral: false
stateful: false
profiles:
  - macvlan-profile
config:
  cloud-init.network-config: |2+
      version: 2
      ethernets:
        eth0:                 # Externes LAN, fixed IP-Adress
          dhcp4: true
          dhcp6: true
          macaddress: ba:e4:64:bc:81:d7
        eth1:               # Internes Lan, dhcp
          dhcp4: true
          dhcp6: true
  cloud-init.user-data: |+
    #cloud-config
    locale: C.UTF-8
    timezone: Europe/Vienna
    package_update: true
    package_upgrade: true
    package_reboot_if_required: true
    packages:
      - apt-utils
      - dialog
      - iproute2
    runcmd:
      - [touch, /tmp/cloud_init_completed]
  image.architecture: amd64
  image.description: ubuntu 24.04 LTS amd64 (minimal release) (20250727)
  image.label: minimal release
  image.os: ubuntu
  image.release: noble
  image.serial: '20250727'
  image.type: squashfs
  image.version: '24.04'
devices:
  eth1:
    network: lxdfan0
    type: nic
  root:
    path: /
    pool: remote
    size: 5GiB
    type: disk