{
 "title": "Docker Registry",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "query_result(registry_http_in_flight_requests)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{app=\"$app\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$app\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "registry_storage_action_seconds",
   "type": "stat",
   "description": "The number of seconds that the storage action takes",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "singlestat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_http_requests_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{instance=\"$instance\", handler=\"base\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\"}[10m])"
    }
   ]
  },
  {
   "title": "Catalog HTTP Request Latencies in seconds (catalog)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "rate(registry_http_in_flight_requests{handler=\"catalog\"}[10m])"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(registry_storage_action_seconds_sum{instance=\"$instance\"}[2m]) * 1000",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{handler=\"blob\"}"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_in_flight_requests{handler=\"blob_upload\"}[10m])"
    }
   ]
  },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_in_flight_requests{handler=\"manifest\"}[10m])"
    }
   ]
  }
 ]
}