{
 "title": "Slainte",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Node Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{container=\"kube-rbac-proxy\"}"
    },
    {
     "expr": "node_load5{container=\"kube-rbac-proxy\"}"
    },
    {
     "expr": "node_load15{container=\"kube-rbac-proxy\"}"
    }
   ]
  },
  {
   "title": "Slainte Nodes Anzahl",
   "type": "stat",
   "description": "Zeigt  wieviele Nodes es im Cluster gibr",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info{})", "legendFormat": "Anzahl Nodes" }
   ]
  },
  {
   "title": "Nicht verfügbare Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{})"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=~'/dev/mmcblk0p2'}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes{}" }
   ]
  },
  {
   "title": "Netzwerk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Temperatursensor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\", zone=\"0\"}"
    }
   ]
  }
 ]
}