---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientserver
  namespace: slainte
  labels:
    app: clientserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientserver
  template:
    metadata:
      labels:
        app: clientserver
    spec:
      containers:
        - name: clientserver
          image: registry.k8s.slainte.at/examples/clientserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clientserver
  namespace: slainte
spec:
  selector:
    app: clientserver
  ports:
    - port: 80
      targetPort: 80
---