############################################################################################
#
# Settings for sshd
#
############################################################################################
Protocol 2
AddressFamily any
Port 22
ClientAliveInterval 30000
ClientAliveCountMax 50
IgnoreRhosts yes
HostbasedAuthentication no
ChallengeResponseAuthentication no
X11Forwarding yes
X11DisplayOffset 10
TCPKeepAlive yes
AcceptEnv LANG LC_*
LoginGraceTime 2m
PermitRootLogin no
StrictModes no
MaxAuthTries 6
MaxSessions 10
PermitEmptyPasswords no
#AllowGroups users admin ansible
#AllowUsers ansible
AllowTcpForwarding no
Compression no
AuthorizedKeysFile ~/.ssh/authorized_keys
PubkeyAuthentication yes
PasswordAuthentication no
############################################################################################
