#!/bin/bash
############################################################################################
# File Generator
#
# usage: ./filegenerator.sh <FQFN of the file to be read>
############################################################################################
#shopt -o -s errexit # Terminates  the shell script if a command returns an error code.
#shopt -o -s xtrace  # Displays each command before it is executed.
shopt -o -s nounset  # No Variables without definition

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    echo "Usage: $0 <FQFN of the file to be read>"
    exit 1
fi

FQFN=$1
mf=$(cat $FQFN | base64 )
#echo $mf

TMPFILE=$(mktemp -p /tmp tmp.XXXXXX)
cat << EOF  > $TMPFILE
      # This file is $FQFN generated by $0
      - path: <set your path here eg. /root/.ssh/id_rsa>
        owner: <set your owner:group here eg. root:root>
        permissions: <set your permissions here eg.  0o600>
        defer: true
        encoding: base64
        content: |
EOF

while IFS= read -r line
do
    echo "          $line" >> $TMPFILE
done <<< "${mf}"  

cat $TMPFILE
rm $TMPFILE