"""
instancegenerator.py
Generates LXD instance configuration YAML and start script from templates.
Usage:
    python instancegenerator.py --project=<LXD project> --profile=<LXD profile> --image=<LXD Image Name> --template_dir=<template directory> --name=<instance name>
Prerequisites:
    - Python 3.x
    - Template files in the specified template directory
    - Write permissions in the output directory
"""

import yaml
import os
from datetime import datetime
import sys
import getopt
import base64

def load_template(path):
    if not os.path.isfile(path):
        print(f"Error: Template file not found: {path}", file=sys.stderr)
        sys.exit(2)
    text=""
    with open(path, 'r') as f:
        text+=f.read()
    return text

def load_files(path,template_dir):
    if not os.path.isfile(path):
        print(f"Error: Template file not found: {path}", file=sys.stderr)
        sys.exit(2)
    text=""
    with open(path, 'r') as f:
        for line in f:
            if "content:" in line:
                filename = line.strip().split(":", 1)[1].strip()
                file_path = os.path.join(template_dir, filename)
                if os.path.isfile(file_path):
                    file_data = load_template(file_path)
                    # Encode file_data to base64 and split into multiple lines (max 76 chars per line)
                    file_data = base64.b64encode(file_data.encode()).decode()
                    file_data = '\n          '.join([file_data[i:i+76] for i in range(0, len(file_data), 76)])
                    line = "        content: |\n          " + file_data + "\n"
            text += line
    return text

def generate_instance_yaml(project, profile, image, template_dir, name_instance):
    print(f"Generating instance YAML for '{name_instance}'...")
    try:

        yaml_data = (
            "# Generated by instancegenerator at https://github.com/Alfred-Sabitzer/microk8s-ubuntu/tree/main/setup/MicroCloud/InstanceGenerator \n"
            "# Please change accordingly\n"
            "project: "+project+"\n"
            "name: "+name_instance+"\n"
            "description: "+project+" "+image+" "+profile+"\n"
            "profiles:\n"
            "    - "+profile+"\n"
        )

        path = os.path.join(template_dir, f"image/{image}_image.yaml")
        yaml_data += load_template(path)

        path = os.path.join(template_dir, f"profile/{profile}/profile.yaml")
        yaml_data += load_template(path)

        yaml_data += "config:\n"

        catch=""
        path = os.path.join("./template/cloud-config-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="  cloud-init.user-data: |\n"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"profile/{profile}/config/cloud-init.user-data/cloud-config.yaml")
            if os.path.isfile(path):
                catch="  cloud-init.user-data: |\n"
                catch += load_template(path)
            path = os.path.join("./template/cloud-config.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="  cloud-init.user-data: |\n"
                catch += load_template(path)
        yaml_data += catch

        yaml_data += ("\n\n    # this are the standard-packages\n"
                      "    packages:\n"
                      "      - bash\n"
                      "      - openssh\n"
        )

        catch=""
        path = os.path.join("./template/packages-replace.yaml") # Check local override first
        if os.path.isfile(path):
            #catch="\n    packages:"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"profile/{profile}/config/cloud-init.user-data/packages.yaml")
            if os.path.isfile(path):
                #catch="\n    packages:"
                catch += load_template(path)
            path = os.path.join("./template/packages.yaml")
            if os.path.isfile(path):
                #if catch=="":
                #    catch="\n    packages:"
                catch += load_template(path)
        yaml_data += catch

        catch=""
        path = os.path.join("./template/users-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="\n    users:\n"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"profile/{profile}/config/cloud-init.user-data/users.yaml")
            if os.path.isfile(path):
                catch="\n    users:\n"
                catch += load_template(path)
            path = os.path.join("./template/users.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="\n    users:\n"
                catch += load_template(path)
        yaml_data += catch

        catch=""
        path = os.path.join("./template/groups-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="\n    groups:\n"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"profile/{profile}/config/cloud-init.user-data/groups.yaml")
            if os.path.isfile(path):
                catch="\n    groups:\n"
                catch += load_template(path)
            path = os.path.join("./template/groups.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="\n    groups:\n"
                catch += load_template(path)
        yaml_data += catch


        catch=""
        path = os.path.join("./template/write_files-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="\n    write_files:\n"
            catch += load_files(path,"./template/")
        else:
            path = os.path.join(template_dir, f"profile/{profile}/write_files.yaml")
            if os.path.isfile(path):
                catch="\n    write_files:\n"
                catch += load_files(path,template_dir+"/files")
            path = os.path.join("./template/write_files.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="\n    write_files:\n"
                catch += load_files(path,"./template/")
        yaml_data += catch

        catch=""
        path = os.path.join("./template/runcmd-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="\n    runcmd:\n"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"image/{image}_runcmd.yaml")
            if os.path.isfile(path):
                catch="\n    runcmd:\n"
                catch += load_template(path)
            path = os.path.join("./template/runcmd.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="\n    runcmd:\n"
                catch += load_template(path)
        yaml_data += catch

        catch=""
        path = os.path.join("./template/devices-replace.yaml") # Check local override first
        if os.path.isfile(path):
            catch="\ndevices:\n"
            catch += load_template(path)
        else:
            path = os.path.join(template_dir, f"profile/{profile}/devices.yaml")
            if os.path.isfile(path):
                catch="\ndevices:\n"
                catch += load_template(path)
            path = os.path.join("./template/devices.yaml")
            if os.path.isfile(path):
                if catch=="":
                    catch="\ndevices:\n"
                catch += load_template(path)
        yaml_data += catch

        launch=""
        path = os.path.join(template_dir, f"image/{image}_launch.yaml")
        with open(path, 'r') as f:
            launch+=f.read()

        print(f"Writing instance YAML to '{name_instance}.yaml'...")
        with open(f"{name_instance}.yaml", 'w') as f:
            f.write(yaml_data)

        print(f"Writing start script to '{name_instance}.sh'...")
        start_script = (
            "#!/bin/bash\n"
            "############################################################################################\n"
            f"# Install {name_instance}\n"
            "# https://documentation.ubuntu.com/lxd/latest/howto/instances_create/\n"
            "# Images are from https://images.lxd.canonical.com/\n"
            "# see as well https://documentation.ubuntu.com/lxd/latest/howto/images_manage/\n"
            "# and https://documentation.ubuntu.com/lxd/latest/howto/images_remote/\n"
            "############################################################################################\n"
            "#shopt -o -s errexit # Terminates  the shell script if a command returns an error code.\n"
            "#shopt -o -s xtrace  # Displays each command before it is executed.\n"
            "shopt -o -s nounset  # No Variables without definition\n"
            f"app=\"{name_instance}\"\n"
            "lxc list ${app}\n"
            "lxc delete ${app} --force\n"
            f"lxc init {launch} "+"${app} < ${app}.yaml\n"
            "lxc start ${app}\n"
            "lxc list ${app}\n"
            "echo \"${app} Installed\"\n"
        )
        with open(f"{name_instance}.sh", 'w') as f:
            f.write(start_script)
        print("Generation complete.")
    except Exception as e:
        print(f"Error during generation: {e}", file=sys.stderr)
        sys.exit(3)

def main(argv):
    opts, args = getopt.getopt(argv,"h:o:p:i:d:n",["help","project=","profile=","image=","template_dir=","name="])
    project="default"
    profile="default"
    image="ubuntu"
    template_dir="./templates"
    name_instance="demo"

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            print(__doc__)
            sys.exit()
        elif opt in ("-o", "--project"):
            project = arg
        elif opt in ("-p", "--profile"):
            profile = arg
        elif opt in ("-i", "--image"):
            image = arg
        elif opt in ("-d", "--template_dir"):
            template_dir = arg
        elif opt in ("-n", "--name"):
            name_instance = arg
#
# Convention: all lowercase 
# because of ssh and other tools
#

    project = project.lower()
    profile = profile.lower()
    image = image.lower()
    name_instance = name_instance.lower()

    generate_instance_yaml(project, profile, image, template_dir, name_instance)


if __name__ == "__main__":
    if len(sys.argv) > 2:
        main(sys.argv[1:])
    else:
        print(__doc__)
