import yaml
import os
from datetime import datetime
import os
import sys
import getopt

def load_template(template_dir, name):
    path = os.path.join(template_dir, f"{name}")
    if not os.path.isfile(path):
        raise FileNotFoundError(f"Template file not found: {path}")
    with open(path, 'r') as f:
        return f.read()

def generate_instance_yaml(project, profile, image, type, template_dir, name_instance):
  
# name: LoadBalancer
# description: Balancing all Requests
# project: default
    project_data = load_template(template_dir, "project_"+project+".yaml")
    project_data = project_data +"\nname: "+name_instance+"\n"
    project_data = f'{project_data}description: "{profile} {image} {type} generated on {datetime.now()}"\n'

# type: container
# architecture: x86_64
# ephemeral: false
# stateful: false
    image_data = load_template(template_dir, "image_"+image+".yaml")

# profiles:
#   - infrastructure
    profile_data = load_template(template_dir, "profile_"+profile+".yaml")

# config:
#   image.architecture: amd64
#   image.description: ubuntu 24.04 LTS amd64 (release) (20250805)
#   image.label: release
#   image.os: ubuntu
#   image.release: noble
#   image.serial: '20250805'
#   image.type: squashfs
#   image.version: '24.04'
    image_config = load_template(template_dir, "image_"+image+".config")


#  limits.memory: 1GiB
#  snapshots.schedule.stopped: 'true'
#  snapshots.schedule: '@weekly'
#  snapshots.expiry: 4w
    profile_config = load_template(template_dir, "profile_"+profile+".config")

#   cloud-init.user-data: |
#     #cloud-config
#     locale: C.UTF-8
#     timezone: Europe/Vienna
#     package_update: true
#     package_upgrade: true
#     package_reboot_if_required: true
#     packages:
#       - apt-utils
#       - iputils-ping
#       - podman
#       - podman-compose
    type_data = load_template(template_dir, "type_"+type+".yaml")

# devices:
#   eth0:
#     network: default
#     type: nic
#   root:
#     path: /
#     pool: default
#     size: 5GiB
#     type: disk
    profile_device = load_template(template_dir, "profile_"+profile+".device")

    launch = load_template(template_dir, "image_"+image+".launch")

    instance_config = "# Generated by instancegenerator at https://github.com/Alfred-Sabitzer/microk8s-ubuntu/tree/main/setup/MicroCloud/InstanceGenerator\n# Please change accordingly\n"+project_data + image_data + profile_data + image_config + profile_config + type_data + profile_device

    with open(name_instance + ".yaml", 'w') as f:
        f.write(instance_config)
        start_script = (
            "#!/bin/bash\n"
            "############################################################################################\n"
            "#\n"
            f"# Install {name_instance}\n"
            "# https://documentation.ubuntu.com/lxd/latest/howto/instances_create/\n"
            "# Images are from https://images.lxd.canonical.com/\n"
            "# see as well https://documentation.ubuntu.com/lxd/latest/howto/images_manage/\n"
            "# and https://documentation.ubuntu.com/lxd/latest/howto/images_remote/\n"
            "############################################################################################\n"
            "#shopt -o -s errexit    #—Terminates  the shell script  if a command returns an error code.\n"
            "#shopt -o -s xtrace #—Displays each command before it is executed.\n"
            "shopt -o -s nounset #- No Variables without definition\n"
            "\n"
            f"app=\"{name_instance}\"\n"
            "\n"
            "lxc list\n"
            "lxc delete ${app} --force\n"
            f"lxc init {launch} "+"${app} < ${app}.yaml\n"
            "lxc start ${app}\n"
            "lxc list ${app}\n"
            "\n"
            "echo \"${app} Installed\"\n"
        )

    with open(name_instance + ".sh", 'w') as f:
        f.write(start_script)

def main(argv):
    opts, args = getopt.getopt(argv,"h:o:p:i:t:d:n",["help","project=","profile=","image=","type=","template_dir=","name="])
    project="default"
    profile="default"
    image="ubuntu"
    type="minimal"
    template_dir="./templates"
    name_instance="demo"

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            print("Usage: --project=<LXD project> --profile=<LXD profile> --image=<LXD Image Name> --type=<minimal or full> --template_dir=<default .template> --output_file=<default instance.yaml>")
            sys.exit()
        elif opt in ("-o", "--project"):
            project = arg
        elif opt in ("-p", "--profile"):
            profile = arg
        elif opt in ("-i", "--image"):
            image = arg
        elif opt in ("-t", "--type"):
            type = arg
        elif opt in ("-d", "--template_dir"):
            template_dir = arg
        elif opt in ("-n", "--name"):
            name_instance = arg
    generate_instance_yaml(project, profile, image, type, template_dir, name_instance)

if __name__ == "__main__":
    if len(sys.argv) > 2:
        main(sys.argv[1:])
    else:
        print("Usage: --project=<LXD project> --profile=<LXD profile> --image=<LXD Image Name> --type=<minimal or full> --template_dir=<default .template> --output_file=<default instance.yaml>")
