---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr
  namespace: observability
  labels:
    app: ceph
spec:
  ports:
    - name: metrics
      port: 9283
      targetPort: 9283
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ceph-mgr
  namespace: observability
  labels:
    kubernetes.io/service-name: ceph-mgr
addressType: IPv4
ports:
  - name: http-prom
    port: 9283
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.0.191
      - 192.168.0.192
      - 192.168.0.193
      - 192.168.0.194
    conditions:
      ready: true
---