---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: gpg
  name: gpg
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpgsecret
  namespace: gpg
  labels:
    app: gpgsecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpgsecret
  template:
    metadata:
      labels:
        app: gpgsecret
    spec:
      containers:
        - name: gpgsecret
          image: registry.k8s.slainte.at/gpgsecret:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config  # Same Time as Node
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: gpgsecret
  namespace: gpg
spec:
  selector:
    app: gpgsecret
  ports:
    - port: 80
      targetPort: 80
---