---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: k8s-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: k8s-selfsigned-ca
  secretName: k8s-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: k8s-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: k8s-ca-issuer
spec:
  ca:
    secretName: k8s-root-secret