from docker.io/library/alpine:latest

LABEL maintainer="alfred@slainte.at"
LABEL Description="Test for Harbor"

# Variable
ENV LANG=de_DE.UTF-8
ENV LANGUAGE=de_DE.UTF-8
ENV LC_ALL=de_DE.UTF-8

# timezone support
ENV TZ=Europe/Vienna
RUN apk add --update tzdata &&\
    cp /usr/share/zoneinfo/${TZ} /etc/localtime &&\
    echo $TZ > /etc/timezone && \
    rm -rf /usr/share/zoneinfo

COPY *.sh /
RUN rm /do.sh
RUN chmod 755 /*.sh

CMD ["sh", "/dummy.sh"]
