apiVersion: batch/v1
kind: Job
metadata:
  name: softhsm-job
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: softhsm
        image: alpine:latest
        volumeMounts:
          - name: softhsm-data
            mountPath: /var/lib/softhsm
        env:
          - name: SOFTHSM2_CONF
            value: "/etc/softhsm2.conf"
        command:
          - "sh"
          - "-c"
          - |
            apk update && apk upgrade && \
            apk add --update tzdata && \
            cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && \
            echo "Europe/Vienna" > /etc/timezone && \
            apk add --no-cache softhsm opensc && \
            softhsm2-util --init-token --free --label "Openbao" --pin ${K8S_OPENBAO_USER_PIN} --so-pin ${K8S_OPENBAO_SO_PIN} && \
            softhsm2-util --show-slots && \
            pkcs11-tool --show-info --module /usr/lib/softhsm/libsofthsm2.so && \
            pkcs11-tool --list-slots --module /usr/lib/softhsm/libsofthsm2.so && \
            pkcs11-tool --module "/usr/lib/softhsm/libsofthsm2.so" --token-label Openbao --so-pin ${K8S_OPENBAO_SO_PIN} --pin ${K8S_OPENBAO_USER_PIN} --keypairgen  --key-type rsa:4096 --label bao-root-key-rsa && \
            pkcs11-tool --list-slots --module /usr/lib/softhsm/libsofthsm2.so && \
            cp /usr/lib/softhsm/libsofthsm2.so /var/lib/softhsm/libsofthsm2.so && \
            sleep 10
      # https://cyberhashira.github.io/notes/pkcs11/SoftHSM2.html
      # https://openbao.org/docs/configuration/seal/pkcs11/
      volumes:
      - name: softhsm-data
        persistentVolumeClaim:
          claimName: softhsm-pvc
      restartPolicy: Never
  backoffLimit: 4
