---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: slainte
  annotations:
    linkerd.io/inject: enabled
  name: slainte
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: admin
  annotations:
    linkerd.io/inject: enabled
  name: admin
spec:
  finalizers:
    - kubernetes
---
# Kein Linkerd für Tests
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: default
  annotations:
    linkerd.io/inject: disabled
  name: default
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kube-system
  annotations:
    linkerd.io/inject: disabled
  name: kube-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kube-public
  annotations:
    linkerd.io/inject: disabled
  name: kube-public
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kube-node-lease
  annotations:
    linkerd.io/inject: disabled
  name: kube-node-lease
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ingress
  annotations:
    linkerd.io/inject: disabled
  name: ingress
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: observability
  annotations:
    linkerd.io/inject: disabled
  name: observability
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: starboard-system
  annotations:
    linkerd.io/inject: disabled
  name: starboard-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: argocd
  annotations:
    linkerd.io/inject: disabled
  name: argocd
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: linkerd-viz
  annotations:
    linkerd.io/inject: disabled
  name: linkerd-viz
spec:
  finalizers:
    - kubernetes
---