apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    kubernetes.io/metadata.name: rook-ceph
    app.kubernetes.io/name: rook-ceph
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-sa
  namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-writer
  namespace: rook-ceph
  labels:
    security: cis
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: rook-ceph
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasspodstatuses
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-ceph-swb
  namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    openbao.mount: rook-ceph
roleRef:
  kind: Role
  name: rook-ceph-writer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: rook-ceph-sa
    namespace: rook-ceph