---
# ServiceMonitor for Grafana to enable Prometheus scraping of its metrics.
# The release label matches the kube-prometheus-stack configuration in this environment.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prom-stack-harbor
  namespace: observability
  annotations:
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: observability
  labels:
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/version: 12.1.0
    helm.sh/chart: harbor-1.0.0
    release: kube-prom-stack # label used by kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prom-stack
      app.kubernetes.io/name: harbor
  namespaceSelector:
    matchNames:
      - ${NAMESPACE}
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      interval: 30s
      scrapeTimeout: 10s
---