apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-harbor
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
spec:
  secretStoreRef:
    name: harbor-eso
    kind: SecretStore
  refreshInterval: 24h
  refreshPolicy: Periodic
  target:
    name: postgres
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        annotations:
          managed-by: keepass-to-eso-openbao-py
        labels:
          managed-by: keepass-to-eso-openbao-py
  data:
    - secretKey: password
      remoteRef:
        key: harbor/postgres
        property: password
        decodingStrategy: None
    - secretKey: notes
      remoteRef:
        key: harbor/postgres
        property: notes
        decodingStrategy: None