apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registrysecret
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-harbor
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
spec:
  secretStoreRef:
    name: harbor-eso
    kind: SecretStore
  refreshInterval: 24h
  refreshPolicy: Periodic
  target:
    name: registrysecret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        annotations:
          managed-by: keepass-to-eso-openbao-py
        labels:
          managed-by: keepass-to-eso-openbao-py
  data:
    - secretKey: username
      remoteRef:
        key: harbor/registrysecret
        property: username
        decodingStrategy: None
    - secretKey: password
      remoteRef:
        key: harbor/registrysecret
        property: password
        decodingStrategy: None
    - secretKey: url
      remoteRef:
        key: harbor/registrysecret
        property: url
        decodingStrategy: None
    - secretKey: notes
      remoteRef:
        key: harbor/registrysecret
        property: notes
        decodingStrategy: None
