apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: registrysecret
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-harbor
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
data:
  username: YWRtaW4=
  password: d1RNYmJKMkMyVVVnekxMdjVGdWQ=
  url: aHR0cHM6Ly9oYXJib3IudGVzdC5zbGFpbnRlLmF0
  notes: S2V5IGZvciBhY2Nlc3NpbmcgdGhlIHJlZ2lzdHJ5
