apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: registrycredentials
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-harbor
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
data:
  username: YWRtaW4=
  password: TXRIUHA1SkFTTHFuUG8yVVo5ekY=
  url: aHR0cHM6Ly9oYXJib3IudGVzdC5zbGFpbnRlLmF0
  notes: 
    ICBjcmVkZW50aWFsczoKICAgIHVzZXJuYW1lOiAiaGFyYm9yX3JlZ2lzdHJ5X3VzZXIiCiAgICBwYXNzd29yZDogImhhcmJvcl9yZWdpc3RyeV9wYXNzd29yZCIKICAgICMgSWYgdXNpbmcgZXhpc3RpbmdTZWNyZXQsIHRoZSBrZXkgbXVzdCBiZSBSRUdJU1RSWV9QQVNTV0QgYW5kIFJFR0lTVFJZX0hUUEFTU1dECiAgICBleGlzdGluZ1NlY3JldDogIiI=
  REGISTRY_HTPASSWD: NFM3a1R4U2lWMmc3UVpiUXF4WnA=
  REGISTRY_PASSWD: NFM3a1R4U2lWMmc3UVpiUXF4WnA=
