apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secretadminpassword
  namespace: harbor
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-harbor
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
data:
  username: YWRtaW4=
  password: NE51Q04yejJGamhoN1VlYWpYYUY=
  url: aHR0cHM6Ly9oYXJib3IudGVzdC5zbGFpbnRlLmF0
  notes: WnVnYW5nIHp1IEhhcmJvcg==
  secretKey: S0x0ZlJYYUE3eDdmZEZydw==
