---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goencrypt
  namespace: slainte
  labels:
    app: goencrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goencrypt
  template:
    metadata:
      labels:
        app: goencrypt
    spec:
      containers:
        - name: goencrypt
          image: registry.k8s.slainte.at/examples/goencrypt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goencrypt
  namespace: slainte
spec:
  selector:
    app: goencrypt
  ports:
    - port: 80
      targetPort: 80
---