apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jivacsidefault
  namespace: default
  labels:
    app: bbopenebs
    storage: openebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath
  namespace: default
  labels:
    app: bbopenebs
    storage: openebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Mi
