---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: prometheus-external-se
  namespace: istio-system
spec:
  hosts:
    - prometheus-ceph-external.local
  ports:
    - number: 9283
      name: http-prom
      protocol: HTTP
      targetPort: 9283
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 192.168.0.191
      ports:
        http-prom: 9283
    - address: 192.168.0.192
      ports:
        http-prom: 9283
    - address: 192.168.0.193
      ports:
        http-prom: 9283
    - address: 192.168.0.194
      ports:
        http-prom: 9283
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-egress-gateway
  namespace: istio-system
spec:
  selector:
    # must match the labels on the egress gateway workload
    istio: egressgateway
  servers:
    - port:
        number: 9283
        name: http-prom
        protocol: HTTP
      hosts:
        - prometheus-ceph-external.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-prometheus
  namespace: istio-system
spec:
  host: prometheus-egress-gateway.istio-system.svc.cluster.local
  subsets:
  - name: prometheus-ceph-external
---
# VirtualService in istio-system: route requests received by the egress gateway to the external host
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-egress-routing
  namespace: istio-system
spec:
  hosts:
    - prometheus-ceph-external.local
  gateways:
    - istio-system/prometheus-egress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus-ceph-external.local
            port:
              number: 9283
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: prometheus-egress-sidecar
  namespace: istio-system
spec:
  # no workloadSelector -> applies to all workloads in istio-system namespace
  egress:
    - hosts:
        - "./*"                         # allow services in same namespace
        - "istio-system/*"
        - "kube-system/*"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: prometheus-ceph-external
  namespace: istio-system
  labels:
    kubernetes.io/service-name: prometheus-ceph-external
addressType: IPv4
ports:
  - name: http-prom
    port: 9283
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.0.191
      - 192.168.0.192
      - 192.168.0.193
      - 192.168.0.194
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ceph-external
  namespace: istio-system
spec:
  ports:
    - name: http-prom
      port: 9283
      targetPort: 9283
      protocol: TCP
  clusterIP: None    # headless service - backed by manual Endpoints
---