---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rook-external-se
  namespace: istio-system
spec:
  hosts:
    - rook-ceph-external.local
  ports:
    - number: 6789
      name: http-rook
      protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 192.168.0.191
      ports:
        http-rook: 6789
    - address: 192.168.0.192
      ports:
        http-rook: 6789
    - address: 192.168.0.193
      ports:
        http-rook: 6789
    - address: 192.168.0.194
      ports:
        http-rook: 6789
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rook-egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 6789
        name: http-rook
        protocol: HTTP
      hosts:
        - rook-ceph-external.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-rook
  namespace: istio-system
spec:
  host: rook-egress-gateway.istio-system.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: rook-ceph-external
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rook-egress-routing
  namespace: istio-system
spec:
  hosts:
    - rook-ceph-external.local
  gateways:
    - istio-system/rook-egress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: rook-ceph-external.local
            port:
              number: 6789
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: rook-egress-sidecar
  namespace: istio-system
spec:
  egress:
    - hosts:
        - "./*"
        - "istio-system/*"
        - "kube-system/*"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: rook-ceph-external
  namespace: istio-system
  labels:
    kubernetes.io/service-name: rook-ceph-external
addressType: IPv4
ports:
  - name: http-rook
    port: 6789
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.0.191
    conditions:
      ready: true
  - addresses:
      - 192.168.0.192
    conditions:
      ready: true
  - addresses:
      - 192.168.0.193
    conditions:
      ready: true
  - addresses:
      - 192.168.0.194
    conditions:
      ready: true
  - addresses:
      - 192.168.0.194
    conditions:
      ready: true
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-external
  namespace: istio-system
spec:
  ports:
    - name: http-rook
      port: 6789
      targetPort: 6789
      protocol: TCP
  clusterIP: None
---