apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull
  namespace: kyverno
  labels:
    app.kubernetes.io/managed-by: keepass-to-eso-openbao-py
  annotations:
    keepassxc.folderPath: root-kyverno
    keepassxc.database: home-alfred-kdbx-kdbx-k8stest-kdbx
spec:
  secretStoreRef:
    name: kyverno-eso
    kind: SecretStore
  refreshInterval: 24h
  refreshPolicy: Periodic
  target:
    name: harbor-pull
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          managed-by: keepass-to-eso-openbao-py
        labels:
          managed-by: keepass-to-eso-openbao-py
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: kyverno/harbor-pull
        property: .dockerconfigjson
        decodingStrategy: None
